#!/bin/sh
# hybrid-d77 :: our own image variants ("sway", and "niri" since
# 2026-09-25), via chimera-live's own mklive-image.sh -b flag mechanism
# (see vendor/chimera-live/mklive-image.sh's "sway"/"niri" cases).
#
# h77-dots/h77-sway-dots are built via container/cbuild.Containerfile +
# cbuild-entrypoint.sh into a real local apk repo at cbuild-out/hybrid/
# (run that first if it doesn't exist yet -- this script does NOT
# bootstrap it). apk's -r/--repository natively accepts a local
# filesystem path, no different from a URL (confirmed against
# mklive.sh's own -r help text: "Path to apk repository."), so our
# local repo is just another -r entry alongside the two real
# repo.chimera-linux.org ones.
#
# Usage: iso/mklive-d77.sh [sway|niri] [extra mklive.sh args...]
# (variant defaults to sway). The ISO is named
# hybrid-d77-live-ARCH-YYYYMMDD-VARIANT.iso, same scheme as d77void's
# own d77void-live-ARCH-DATE-VARIANT.iso, via mklive.sh's own -o
# (its default would be chimera-linux-ARCH-LIVE-DATE-VARIANT.iso).
set -e
VARIANT=sway
case "${1:-}" in
	sway|niri) VARIANT="$1"; shift ;;
esac
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SELF_DIR/.." && pwd)"
LOCAL_REPO="$REPO_ROOT/cbuild-out/hybrid"

if [ ! -d "$LOCAL_REPO" ]; then
	echo "!! $LOCAL_REPO doesn't exist yet -- run container/cbuild.Containerfile" >&2
	echo "   first (builds h77-dots/h77-sway-dots into real .apk files)." >&2
	exit 1
fi

# mklive.sh's own -k defaults to vendor/chimera-live/keys/ (the real
# Chimera per-arch signing keys, needed to trust the main/user repos)
# and REPLACES that default entirely if -k is passed at all -- so our
# own key (generated by cbuild keygen, copied to cbuild-out/*.rsa.pub)
# is merged into a throwaway keys dir alongside copies of the real
# ones, rather than overriding -k with only our key (which would leave
# main/user unverifiable) or committing our key into the vendored
# keys/ dir (it's regenerated per-session, not a stable identity).
KEYDIR="$REPO_ROOT/iso/.keys"
rm -rf "$KEYDIR"
mkdir -p "$KEYDIR"
cp "$SELF_DIR/../vendor/chimera-live/keys/"*.pub "$KEYDIR/"
cp "$REPO_ROOT/cbuild-out/"*.rsa.pub "$KEYDIR/" 2>/dev/null || {
	echo "!! no *.rsa.pub in cbuild-out/ -- our own repo's packages" >&2
	echo "   won't be trusted (apk will refuse to install them)." >&2
	exit 1
}

cd "$SELF_DIR/../vendor/chimera-live"
# -r main is passed explicitly: mklive.sh's own default repo only kicks
# in when NO -r is given at all, so once we add -r for the `user` tier
# (needed for greetd/udiskie/seatd) and our own local repo, main has to
# be listed too or it's silently dropped. These have to come BEFORE the
# `build` positional arg: mklive-image.sh forwards its own "$@"
# verbatim onto the end of `mklive.sh -p ... -f ...`, and mklive.sh's
# getopts stops at the first non-flag word -- so anything meant to be a
# real -r/-k/etc option has to precede `build` in THIS invocation too,
# or it lands as a stray positional arg on mklive.sh's side instead of
# being parsed.
#
# NOT `exec`'d (unlike before 2026-09-24): mklive.sh writes its .iso to
# CWD (here, vendor/chimera-live/), never into $REPO_ROOT/iso/ -- same
# real gap container/entrypoint.sh's own comment already documents for
# the container path ("mklive.sh writes the .iso to CWD ... confirmed
# the hard way"). That path is covered by an explicit `cp` there; this
# native-host script had no equivalent because `exec` here replaced
# the whole process before any such step could run, so the ISO was
# silently left behind in vendor/chimera-live/ instead of iso/ -- found
# the same way, running it for real.
ISO_NAME="hybrid-d77-live-$(uname -m)-$(date '+%Y%m%d')-$VARIANT.iso"
./mklive-image.sh -b "$VARIANT" -- \
    -o "$ISO_NAME" \
    -r https://repo.chimera-linux.org/current/main \
    -r https://repo.chimera-linux.org/current/user \
    -r "$LOCAL_REPO" \
    -k "$KEYDIR" \
    build "$@"

echo ">> moving the ISO to $REPO_ROOT/iso/"
mkdir -p "$REPO_ROOT/iso"
mv "$ISO_NAME" "$REPO_ROOT/iso/"
( cd "$REPO_ROOT/iso" && sha256sum "$ISO_NAME" > "$ISO_NAME.sha256" )
ls -lh "$REPO_ROOT/iso/$ISO_NAME"
