#!/bin/sh
# hybrid-d77 :: our own "sway" image variant, via chimera-live's own
# mklive-image.sh -b flag mechanism (see vendor/chimera-live/
# mklive-image.sh's "sway" case, added 2026-09-12).
#
# h77-dots/h77-sway-dots are built via container/cbuild.Containerfile +
# cbuild-entrypoint.sh into a real local apk repo at cbuild-out/hybrid/
# (run that first if it doesn't exist yet -- this script does NOT
# bootstrap it). apk's -r/--repository natively accepts a local
# filesystem path, no different from a URL (confirmed against
# mklive.sh's own -r help text: "Path to apk repository."), so our
# local repo is just another -r entry alongside the two real
# repo.chimera-linux.org ones.
set -e
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SELF_DIR/.." && pwd)"
LOCAL_REPO="$REPO_ROOT/cbuild-out/hybrid"

if [ ! -d "$LOCAL_REPO" ]; then
	echo "!! $LOCAL_REPO doesn't exist yet -- run container/cbuild.Containerfile" >&2
	echo "   first (builds h77-dots/h77-sway-dots into real .apk files)." >&2
	exit 1
fi

# mklive.sh's own -k defaults to vendor/chimera-live/keys/ (the real
# Chimera per-arch signing keys, needed to trust the main/user repos)
# and REPLACES that default entirely if -k is passed at all -- so our
# own key (generated by cbuild keygen, copied to cbuild-out/*.rsa.pub)
# is merged into a throwaway keys dir alongside copies of the real
# ones, rather than overriding -k with only our key (which would leave
# main/user unverifiable) or committing our key into the vendored
# keys/ dir (it's regenerated per-session, not a stable identity).
KEYDIR="$REPO_ROOT/iso/.keys"
rm -rf "$KEYDIR"
mkdir -p "$KEYDIR"
cp "$SELF_DIR/../vendor/chimera-live/keys/"*.pub "$KEYDIR/"
cp "$REPO_ROOT/cbuild-out/"*.rsa.pub "$KEYDIR/" 2>/dev/null || {
	echo "!! no *.rsa.pub in cbuild-out/ -- our own repo's packages" >&2
	echo "   won't be trusted (apk will refuse to install them)." >&2
	exit 1
}

cd "$SELF_DIR/../vendor/chimera-live"
# -r main is passed explicitly: mklive.sh's own default repo only kicks
# in when NO -r is given at all, so once we add -r for the `user` tier
# (needed for greetd/udiskie/seatd) and our own local repo, main has to
# be listed too or it's silently dropped. These have to come BEFORE the
# `build` positional arg: mklive-image.sh forwards its own "$@"
# verbatim onto the end of `mklive.sh -p ... -f ...`, and mklive.sh's
# getopts stops at the first non-flag word -- so anything meant to be a
# real -r/-k/etc option has to precede `build` in THIS invocation too,
# or it lands as a stray positional arg on mklive.sh's side instead of
# being parsed.
exec ./mklive-image.sh -b sway -- \
    -r https://repo.chimera-linux.org/current/main \
    -r https://repo.chimera-linux.org/current/user \
    -r "$LOCAL_REPO" \
    -k "$KEYDIR" \
    build "$@"
