# Mocinha --- live-system installer (cports template; generated by
# packaging/chimera/make-template.sh from a commit on GitHub).
#
# Shipped on a live and removed from the installed system by Mocinha itself
# ([live_only].packages).
pkgname = "mocinha"
pkgver = "0.1.1"
pkgrel = 0
pkgdesc = "Small, modular, platform-aware live-system installer"
license = "MIT"
url = "https://github.com/dani-77/mocinha"
# commit 4f07587d778ed8b2f596033e30ad78b5281efa68
source = f"{url}/archive/refs/tags/0.1.1.tar.gz>mocinha-{pkgver}.tar.gz"
sha256 = "c4eca8b5a87f704416f7899a752f97d0dcb1dc0b77aed7786853f2250dafc111"


def install(self):
    for d in ("mocinha", "bin", "assets", "examples"):
        self.install_files(self.cwd / d, "usr/share/mocinha")
    self.install_bin("packaging/common/mocinha.sh", name="mocinha")
    self.install_file("packaging/common/mocinha-root", "usr/lib/mocinha", mode=0o755)
    self.install_file("packaging/common/mocinha.desktop", "usr/share/applications")
    self.install_file("assets/mocinha-icon-256.png", "usr/share/icons/hicolor/256x256/apps", name="mocinha.png")
    self.install_file("packaging/common/org.mocinha.installer.policy", "usr/share/polkit-1/actions")
    self.install_license("LICENSE")
