# Mocinha --- live-system installer (cports template; generated by
# packaging/chimera/make-source.sh from the Mocinha repository).
#
# Mocinha's repository is private: the source below is not downloadable;
# the remaster's build seeds cbuild's source cache (sources/by_sha256) with
# the archive make-source.sh writes. Shipped on a live and removed from the
# installed system by Mocinha itself ([live_only].packages).
pkgname = "mocinha"
pkgver = "0.1.0.40"
pkgrel = 0
pkgdesc = "Small, modular, platform-aware live-system installer"
license = "custom:none"  # no license file yet (private repository)
url = "https://github.com/dani-77/mocinha"
# commit 3c014d7
source = f"{url}/archive/3c014d7.tar.gz>mocinha-{pkgver}.tar.gz"
sha256 = "4245ca8d3e9d79854fbfbbbad0623bc701bd9717ce4842e250cb92484c1303bc"


def install(self):
    for d in ("mocinha", "bin", "assets", "examples"):
        self.install_files(self.cwd / d, "usr/share/mocinha")
    self.install_bin("packaging/common/mocinha.sh", name="mocinha")
    self.install_file("packaging/common/mocinha-root", "usr/lib/mocinha", mode=0o755)
    self.install_file("packaging/common/mocinha.desktop", "usr/share/applications")
    self.install_file("assets/mocinha-icon-256.png", "usr/share/icons/hicolor/256x256/apps", name="mocinha.png")
    self.install_file("packaging/common/org.mocinha.installer.policy", "usr/share/polkit-1/actions")
